### ISSUE TITLE
JSON viewer is partial

### ISSUE THREAD

**Issue by yoavo-datricks** [dbeaver/cloudbeaver#457] opened 2021-08-29 20:30 UTC
**Is your feature request related to a problem? Please describe.**
When viewing JSON data the JSON viewer does proper spacing but no newlines or indentation.

**Describe the solution you'd like**
The JSON viewer should "prettify" JSON content with new lines, indentation and proper spacing in order the fully understand the JSONs content.

**Comment by kseniiaguzeeva** [comment] 2021-08-30 09:15
Thank you for the report.

**Comment by frank-lam** [comment] 2021-11-15 12:12
@yoavo-datricks 
That's what I thought. Cool

**Comment by kseniiaguzeeva** [comment] 2021-11-24 18:38
The issue is fixed in the latest 21.2.3 release.

**Closed as completed by kseniiaguzeeva** 2021-11-24 18:38 UTC
Labels: xf:data editor
