### ISSUE TITLE
Errors exist in required project(s)

### ISSUE THREAD

**Issue by miltonchirinos44** [dbeaver/cloudbeaver#1027] opened 2022-08-05 13:12 UTC
I'm trying to configure cloud dbeaver in eclipse but I get the following error is like missing source code
![error projects](https://user-images.githubusercontent.com/52106718/183084333-045b2613-f478-4ee6-9004-bb13f90d6ade.png)
I need your help please

**Comment by kseniiaguzeeva** [comment] 2022-08-10 12:31
I close the ticket as duplicate of [Error in all packages in following folders to deploy cloudbeaver in eclipse java](https://github.com/dbeaver/cloudbeaver/issues/988).

**Closed as completed by kseniiaguzeeva** 2022-08-10 12:31 UTC
Labels: duplicate, deployment, xo:eclipse

**Comment by miltonchirinos44** [comment] 2022-08-10 17:55
ok, Sorry @kseniiaguzeeva
