### ISSUE TITLE
Error when connect ck using read only model

### ISSUE THREAD

**Issue by yubobo** [dbeaver/cloudbeaver#627] opened 2022-01-21 09:12 UTC
SQL Error [164]: ClickHouse exception, code: 164, host: cc-clickhouse.oppoer.me, port: 80; Code: 164, e.displayText() = DB::Exception: Cannot modify 'max_result_rows' setting in readonly mode (version 20.8.5.45)

how to modify this error？

**Comment by yubobo** [comment] 2022-01-24 08:26
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [164]: ClickHouse exception, code: 164, host: cc-clickhouse.oppoer.me, port: 80; Code: 164, e.displayText() = DB::Exception: Cannot modify 'max_result_rows' setting in readonly mode (version 20.8.5.45)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:190)
	at io.cloudbeaver.service.sql.WebSQLProcessor.lambda$2(WebSQLProcessor.java:232)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at io.cloudbeaver.service.sql.WebSQLProcessor.readDataFromContainer(WebSQLProcessor.java:229)
	at io.cloudbeaver.service.sql.impl.WebServiceSQL$2.run(WebServiceSQL.java:340)
	at io.cloudbeaver.model.session.WebSession$1.run(WebSession.java:591)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 164, host: cc-clickhouse.oppoer.me, port: 80; Code: 164, e.displayText() = DB::Exception: Cannot modify 'max_result_rows' setting in readonly mode (version 20.8.5.45)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:59)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1099)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:778)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getLastInputStream(ClickHouseStatementImpl.java:692)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:341)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:325)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:320)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:315)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:446)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 8 more
Caused by: java.lang.Throwable: Code: 164, e.displayText() = DB::Exception: Cannot modify 'max_result_rows' setting in readonly mode (version 20.8.5.45)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:54)
	... 19 more

**Comment by kseniiaguzeeva** [comment] 2022-01-24 09:10
Can you connect  to Clickhouse via another application (e.g. DBeaver)? It seems, that the issue is in Clickhouse configuration. Could you please try the advice from [this ticket](https://github.com/enqueue/metabase-clickhouse-driver/issues/20)? Here is [Clickhouse documentation](https://clickhouse.com/docs/en/operations/settings/permissions-for-queries/#settings_readonly).
I'm looking forward to your answer.

**Comment by yubobo** [comment] 2022-01-24 11:49
I use DataGrip to connect to CK successfully.   read only mode.
![image](https://user-images.githubusercontent.com/4443390/150777782-2067fd14-89b0-42e9-82eb-b39ee66d4ed9.png)

**Comment by kseniiaguzeeva** [comment] 2022-01-26 12:24
Thank you for the report. It will be fixed.

**Comment by simsicon** [comment] 2022-01-28 02:21
@kseniiaguzeeva I can confirm that I am experiencing the same problem with  dbeaver/cloudbeaver:21.3.3 docker built. Looking forward to the fix, thank you for your work.

**Comment by kseniiaguzeeva** [comment] 2022-01-28 06:40
Thank you for the report. We are going to fix it in 22.0.0 release.

**Comment by kseniiaguzeeva** [comment] 2022-03-10 13:21
The issue is fixed in the latest release.

**Closed as completed by kseniiaguzeeva** 2022-03-10 13:21 UTC
Labels: xf:connection, x:clickhouse
