### ISSUE TITLE
SQL Editor BUG

### ISSUE THREAD

**Issue by frank-lam** [dbeaver/cloudbeaver#1291] opened 2022-11-17 06:52 UTC
**Describe the bug**
When I select several characters in the SQL editor, the selected text is automatically deleted. When CTRL + A is executed, all text is deleted directly.

Would you like to ask if this is already a BUG? If you fix this problem

**Desktop (please complete the following information):**
 - Browser chrome, safari
 - Version 22.2.4

**Comment by kseniaguzeeva** [comment] 2022-11-17 07:05
I cannot reproduce the bug. Could you please send me a video?

**Comment by frank-lam** [comment] 2022-11-17 07:38
![clickhouse](https://user-images.githubusercontent.com/19153458/202384956-2ac8b037-deb5-47fa-be5a-0314a0877720.gif)

@kseniaguzeeva You can check out this gif of mine

**Comment by miltonchirinos44** [comment] 2022-11-18 14:07
@frank-lam  I think it's more of an error from your browser or your computer seeing your gif

**Comment by Danst-bjtu** [comment] 2022-11-23 07:46
![动画](https://user-images.githubusercontent.com/77576766/203493431-16b5558b-886a-44e7-8255-43e1a9c637f2.gif)

I have the bug gif, there are two bugs:
First, when I move the mouse over a piece of text, the text will disappear, but I did not press the backspace button, and it occurs no matter whether I input Chinese or English.
Secondly, when I input Chinese, multiple letters will appear when I press it once. There is no problem with my keyboard. Just press the keyboard and a string of characters will appear. I don't know what this is about, but it won't happen if I type English. I use the window default Chinese input method，and My browser is edge

**Comment by Danst-bjtu** [comment] 2022-11-23 07:47
![动画](https://user-images.githubusercontent.com/77576766/203494764-7673e916-f9b5-48eb-b566-02d0380d5a1c.gif)

**Comment by qixiaoxinskywalker** [comment] 2022-11-30 02:48
22.2.5:
bugs:
when I double click the word, the word will disapear.
the selected sentences will dispear immediately when I use mouse or use ctrl+c

details:
Everything is ok until I changed my input method to chinese, and when press one key there will be muitiple alphas with underscore. And even though  I changed input method to English the issue still exists, then I can not select or click the word, because they will disapear immediately

However  my old version 22.1.3 does not have the issue.

**Comment by kseniaguzeeva** [comment] 2022-11-30 14:25
Thank you for the details. I reproduced it with chinese input method.

**Comment by Amor7527** [comment] 2023-01-09 02:06
Is this problem fixed?

**Comment by kseniaguzeeva** [comment] 2023-01-09 08:58
Thank you for the reminding. The problem still exists. I'll inform you as soon as it will be fixed.

**Comment by Alexwalt** [comment] 2023-01-12 05:55
I meet the seem bug, input chinese method will delete words on   CloudBeaver version 22.3.2

**Comment by sodarfish** [comment] 2023-02-23 03:25
Same bug reproduced on version 22.3.5.202302200918 :(

**Comment by dariamarutkina** [comment] 2023-03-06 16:42
Fixed in milestone 23.0.0

**Closed as completed** 2023-03-06 16:42 UTC
Labels: xf:sql editor
