### ISSUE TITLE
build.sh variables

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#798] opened 2022-04-28 11:25 UTC
**Describe the bug**

i get an error when i execute the build.sh

**To Reproduce**
1. Go to  cloudbeaver/deploy/build.sh
2. execute ./build.sh

**Screenshots**

![Capture d’écran de 2022-04-28 11-26-19](https://user-images.githubusercontent.com/73563389/165737376-41dd752b-d272-4697-a95a-b7c8eec6f675.png)

I think  i have this error because the build.sh need two arguments for CONFIGURATION_PATH and SAMPLE_DATABASE_PATH and it was not the case with the previous version of cloudbeaver.

#!/bin/bash
set -Eeuo pipefail

#command line arguments
CONFIGURATION_PATH=$1
SAMPLE_DATABASE_PATH=$2

Thank you

**Comment by kseniiaguzeeva** [comment] 2022-04-28 12:40
Thank you for the report. We are going to fix it soon.

**Comment by kseniiaguzeeva** [comment] 2022-04-28 13:03
The issue is fixed in devel branch. The release 22.0.4 will be available next week.

**Closed as completed by kseniiaguzeeva** 2022-04-28 13:03 UTC
Labels: deployment

**Comment by Geronium** [comment] 2022-04-29 10:59
Thank you.
