### ISSUE TITLE
Query returns nothing when column names not defined

### ISSUE THREAD

**Issue by RoryMMMM** [dbeaver/cloudbeaver#528] opened 2021-11-03 10:19 UTC
**Describe the bug**
When doing a query that has ambiguous named columns (like an aggregation) the cloudbeaver query window returns nothing. The same query will return data when run in some other tool (tested with pymssql lib). 

**To Reproduce**
* Running the query "SELECT * FROM my_table WHERE id=1" returns data in both cloudbeaver and pymssql
* Running the query "SELECT count(*) FROM my_table WHERE id=1" returns data with pymssql. In cloudbeaver an empty result window is returned. There doesn't seem to be a warning and the query takes a reasonable amount of time, which leads me to believe it gets executed. 
* Running the query "SELECT count(*) AS 'count' FROM my_table WHERE id=1" returns data with pymssql and cloudbeaver. 
* The query "SELECT 'some_string_constant', * FROM my_table" causes the same odd behaviour. 
* The query "SELECT 'some_string_constant' as 'str_cnst', * FROM my_table" fixes the same odd behaviour. 

**Desktop (please complete the following information):**
 - OS: Service running on ubuntu 21.04, in a docker container, query is run from a Win10 machine via
 - Browser: Chrome 95.0.4638.54 (Official Build) (64-bit)
 - Version:  Docker image dbeaver/cloudbeaver:21.2.0

**Database**
- The DB being queried is a MS SQL Server Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)

**Comment by kseniiaguzeeva** [comment] 2021-11-03 10:42
Could you please tell what database do you use?

**Comment by RoryMMMM** [comment] 2021-11-03 10:44
Added DB version to top page

**Comment by kseniiaguzeeva** [comment] 2021-11-03 10:55
Thank you for the report. Reproduced.
![chrome_nlO3tPanGr](https://user-images.githubusercontent.com/51405061/140048294-deec8039-1158-4b96-b7a7-937d8a14bd4c.png)

**Comment by kseniiaguzeeva** [comment] 2021-11-24 18:38
The issue is fixed in the latest 21.2.3 release.

**Closed as completed by kseniiaguzeeva** 2021-11-24 18:38 UTC
Labels: xf:sql editor, x:sql server
