### ISSUE TITLE
Can you package cloudbeaver with Docker and Docker compose?

### ISSUE THREAD

**Issue by snowdream** [dbeaver/cloudbeaver#24] opened 2020-04-28 07:43 UTC
**Is your feature request related to a problem? Please describe.**

Can you package cloudbeaver with Docker and Docker compose?

**Describe the solution you'd like**
Please package cloudbeaver with Docker and Docker compose

**Comment by FreeSoftwareServers** [comment] 2020-04-28 18:24
This is already under request w/ Issue #13, I just hit a "thumbs up" to show my desire/support for the ticket, perhaps do the same?>

https://github.com/dbeaver/cloudbeaver/issues/13

**Comment by serge-rider** [comment] 2020-04-29 17:34
Yep. Duplicate of #13

**Closed as completed by serge-rider** 2020-04-29 17:34 UTC
Labels: duplicate
