### ISSUE TITLE
About server Database configuration

### ISSUE THREAD

**Issue by yangmeng66** [dbeaver/cloudbeaver#668] opened 2022-02-21 07:30 UTC
hello:

How about server How about replacing database with SQLite database? driver='sqlite' ? url=???

![image](https://user-images.githubusercontent.com/51857567/154908479-d46bcb4a-434c-4360-94d3-f99d8703135b.png)

**Comment by kseniiaguzeeva** [comment] 2022-02-21 12:26
We are going to fix the bug and SQLite database can be used as server database after it. 
When the issue will be fixed, you should write in config files:
```
"database": {
      "driver": "sqlite",
      "url": "jdbc:sqlite:/..."
```
https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration

The ticket is closed as duplicate of https://github.com/dbeaver/cloudbeaver/issues/665

**Closed as completed by kseniiaguzeeva** 2022-02-21 12:26 UTC
Labels: duplicate, xf:local config
