### ISSUE TITLE
change cloudbeaver default database to sqlite failed

### ISSUE THREAD

**Issue by wolfIsNotNoob** [dbeaver/cloudbeaver#665] opened 2022-02-19 09:20 UTC
the default database is h2, I wanna replace it with sqlite;
I only change the cloudbeaver.conf, but it start failed;

**cloudbeaver.conf**
```
{
    server: {
        serverPort: 8978,

        workspaceLocation: "workspace",
        contentRoot: "web",
        driversLocation: "drivers",

        rootURI: "/",
        serviceURI: "/api/",

        productConfiguration: "conf/product.conf",

        expireSessionAfterPeriod: 1800000,

        develMode: false,

        database: {
            driver="sqlite_jdbc",
            url: "jdbc:sqlite:${workspace}/.data/cb.h2.dat",

            createDatabase: true,

            initialDataConfiguration: "conf/initial-data.conf",

            pool: {
                minIdleConnections: 4,
                maxIdleConnections: 10,
                maxConnections: 100
            }
        }
    },
    app: {
        anonymousAccessEnabled: true,
        anonymousUserRole: "user",
        supportsCustomConnections: false,

        publicCredentialsSaveEnabled: true,
        adminCredentialsSaveEnabled: true,

        resourceQuotas: {
            dataExportFileSizeLimit: 10000000,
            sqlMaxRunningQueries: 3,
            sqlResultSetRowsLimit: 100000,
            sqlResultSetMemoryLimit: 2000000
        }
    }
}

```

log
```
2022-02-19 17:16:49.525 - Error initializing database
org.jkiss.dbeaver.DBException: Error updating management database schema
        at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:218)
        at io.cloudbeaver.server.CBApplication.initializeDatabase(CBApplication.java:422)
        at io.cloudbeaver.server.CBApplication.start(CBApplication.java:270)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.jkiss.dbeaver.DBException: Error updating CB schema version
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:108)
        at io.cloudbeaver.server.CBDatabase.initialize(CBDatabase.java:212)
        ... 15 more
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "SEQUENCE": syntax error)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.throwex(DB.java:918)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:52)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.executeScript(SQLSchemaManager.java:175)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.createNewSchema(SQLSchemaManager.java:136)
        at org.jkiss.dbeaver.model.sql.schema.SQLSchemaManager.updateSchema(SQLSchemaManager.java:90)
        ... 16 more

```

**Comment by kseniiaguzeeva** [comment] 2022-02-21 12:27
We are going to fix the bug and SQLite database can be used as a server database.
Thank you for the report.

**Comment by kseniiaguzeeva** [comment] 2022-03-23 07:13
The issue is fixed in the [latest release](https://github.com/dbeaver/cloudbeaver)

**Closed as completed by kseniiaguzeeva** 2022-03-23 07:13 UTC
Labels: xf:local config
