### ISSUE TITLE
Issues with core.user.defaultTheme

### ISSUE THREAD

**Issue by ericsgagnon** [dbeaver/cloudbeaver#532] opened 2021-11-07 09:21 UTC
I've tried setting core.user.defaultTheme: "dark" in conf/product.conf, but every time I go to cloudbeaver in a clean browser session (ie new incognito mode window), it uses light theme. I'd love to be able to get it to use dark theme all the time, including when I'm not logged in. Is there any way to do this?

**Comment by kseniiaguzeeva** [comment] 2021-11-08 13:44
Thank you for the report. We are going to add theme selection support.

**Comment by kseniiaguzeeva** [comment] 2021-11-24 18:38
The issue is fixed in the latest 21.2.3 release.

**Closed as completed by kseniiaguzeeva** 2021-11-24 18:38 UTC
Labels: xf:dark theme

**Comment by frank-lam** [comment] 2022-03-30 08:15
@kseniiaguzeeva 
where to setting the default theme??

**Comment by kseniiaguzeeva** [comment] 2022-03-30 09:21
Could you please try to add the parameter to product.conf (or create `.product.runtime.conf` in local config and add the parameter there):
```
{
 "core": {
   "user": {
     "defaultTheme": light
   }
 }
}
```
You can also see the [article](https://github.com/dbeaver/cloudbeaver/wiki/Product-configuration-parameters) about product parameters.

Please do not hesitate to ask any aditional questions.
