### ISSUE TITLE
Display columns/other info in the DB navigator setting

### ISSUE THREAD

**Issue by kjee87** [dbeaver/cloudbeaver#2294] opened 2024-01-11 17:05 UTC
Hello, 

Is there a feature available in the cloudbeaver to display columns/other info (columns, keys, foreign keys etc) in the db navigator setting, like in dbeaver? If it is already available, may I know the name of the parameter to turn on?

From dbeaver:
<img width="225" alt="Screenshot 2024-01-11 at 9 01 19 AM" src="https://github.com/dbeaver/cloudbeaver/assets/63018897/2b4bedff-f311-4b5e-acb9-ffcd5af05abf">

**Comment by EvgeniaBzzz** [comment] 2024-01-11 18:56
Hi @kjee87!
Yes, it's available. But not in the Navigation tree.
Open any table and switch to the Properties tab.
![image](https://github.com/dbeaver/cloudbeaver/assets/139753579/0de28f4e-b4ba-4fc0-a74f-2ba08736a4fa)

**Comment by kjee87** [comment] 2024-01-11 20:52
Ah, well thank you for the response. 
May I request this feature available in the navigation tree in the cloudbeaver, just like ones in the dbeaver?

**Comment by EvgeniaBzzz** [comment] 2024-01-12 10:27
We have [similar request](https://github.com/dbeaver/cloudbeaver/issues/667). 
I can't say when it will be done or if it will be done. But we will keep in mind that you want this functionality.

**Comment by alejandro-du** [comment] 2024-01-13 17:30
I would dare to say this is a must. It's so useful when working on queries. It's the main reason I'm using DbGate instead of CloudBeaver at the moment. If somebody is interested in implementing this feature, are there any guides or instructions on contributing code? (if that's an actual possibility of course)

**Comment by LonwoLonwo** [comment] 2024-03-11 14:55
This ticket is definitely a duplicate of this ticket: https://github.com/dbeaver/cloudbeaver/issues/667.
So, I'm closing this one. You can vote for the original ticket with any emoji.

**Closed as completed by LonwoLonwo** 2024-03-11 14:55 UTC
Labels: duplicate, xf:navigator, xf:metadata

**Comment by alejandro-du** [comment] 2024-03-11 16:31
It's not a duplicate. #667 is about listing columns in the lateral panel. This (#2294) is about automatically refreshing the information in the panel when DDL is executed in the editor.
