### ISSUE TITLE
logs the requests

### ISSUE THREAD

**Issue by Geronium** [dbeaver/cloudbeaver#488] opened 2021-09-24 21:56 UTC
Hello, 

Can we have a log of the requests that have been made with cloudbeaver by the user ? (maybe it is already possible to configure it, but I did not find)

Thank you

**Comment by kseniiaguzeeva** [comment] 2021-09-27 12:08
Thank you for the feature request. We will implement it, but I do not now a date for now. Another ticket with the same request already exists, so I close this one as the duplicate of https://github.com/dbeaver/cloudbeaver/issues/302.

**Closed as completed by kseniiaguzeeva** 2021-09-27 12:08 UTC
Labels: duplicate, xf:query manager
