### ISSUE TITLE
Pod is crashing because of permission denied 

### ISSUE THREAD

**Issue by MatthiasSchnoeke** [dbeaver/cloudbeaver#1831] opened 2023-07-20 09:37 UTC
How do I deploy a cloudbeaver pod in an openshift cluster without being denied permission?

```
**_Starting Cloudbeaver Server
mkdir: cannot create directory â€˜workspace/.metadataâ€™: Permission denied
<title>Invalid Configuration Location</title>The configuration area at '/.eclipse/248865309_linux_gtk_x86_64/configuration' could not be created.  Please choose a writable location using the '-configuration' command line option.**
```

The pod security context is set automatically: 

      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000800000
        runAsNonRoot: true
        allowPrivilegeEscalation: false

**Comment by MatthiasSchnoeke** [comment] 2023-07-26 11:17
We solve this issue by using a persistent Volume for /workspace directory.

**Comment by TatyanaSsau** [comment] 2023-08-01 07:09
@MatthiasSchnoeke such behavior occurs during a reinstallation - let me know if you are installing the version for the first time?

**Comment by TatyanaSsau** [comment] 2023-08-01 07:14
@MatthiasSchnoeke such behavior occurs during a reinstallation - let me know if you are installing the version for the first time?

**Comment by MatthiasSchnoeke** [comment] 2023-08-10 14:34
Yes, we run in this issue at the first Kuberntes Deployment. As mentioned before, we solve this issue by using a persistent Volume for /workspace directory.

**Comment by TatyanaSsau** [comment] 2023-08-25 09:59
@MatthiasSchnoeke we already fix the similar issue for 23.1.5 version - please just use the tag `ea` for upgrading
https://github.com/dbeaver/team-edition-deploy/tree/ea
Thank you for reporting!

**Comment by Jeffrey778** [comment] 2023-09-19 19:22
Hi @TatyanaSsau , I got a similar issue in docker image `dbeaver/cloudbeaver:23.2.0`, and I already mounted a PVC for dir `/opt/cloudbeaver/workspace`. Please share more details about this bug, then I may find a workaround.
```
Starting Cloudbeaver Server
<title>Invalid Configuration Location</title>The configuration area at '/opt/cloudbeaver/?/.eclipse/248865309_linux_gtk_x86_64/configuration' could not be created.  Please choose a writable location using the '-configuration' command line option.
```

**Comment by ggxed** [comment] 2023-09-22 15:39
What version of openshift are you using?

**Comment by ggxed** [comment] 2023-09-26 10:08
@MatthiasSchnoeke 
@Jeffrey778

**Comment by arhayka** [comment] 2023-10-16 09:43
It’s been a while since an update here. If the issue is still happening, please let us know and provide additional information.

**Comment by MatthiasSchnoeke** [comment] 2023-10-16 12:20
We are running OC 4.11.50.

**Comment by MatthiasSchnoeke** [comment] 2023-10-16 12:24
> @MatthiasSchnoeke we already fix the similar issue for 23.1.5 version - please just use the tag `ea` for upgrading https://github.com/dbeaver/team-edition-deploy/tree/ea Thank you for reporting!

sorry for delay. Does this means, with Image Tag ea we no longer need a persistent Volume for /workspace directory (because of access rights) and all configration data will be stored in maria db?

btw. we are testing cloudbeaver. Is there also an OpenShift Deployment template?

**Comment by ggxed** [comment] 2023-10-18 11:23
Hello, officially we do not support deployments to openshift, only to docker. You can use ready-made community solutions (e.g. https://artifacthub.io/packages/helm/truecharts/cloudbeaver).

Regardless of the version, persistent Volume for /workspace to cloudbeaver will always be needed

**Comment by arhayka** [comment] 2023-11-29 15:24
I'm closing this ticket for the second time. Please feel free to open it if it's still actual.

**Closed as completed by arhayka** 2023-11-29 15:24 UTC
Labels: wait for response, deployment
