### ISSUE TITLE
stackoverflow error when query group with clickhouse

### ISSUE THREAD

**Issue by simsicon** [dbeaver/cloudbeaver#662] opened 2022-02-17 07:03 UTC
When query group array numeric data in clickhouse, causing stackoverflow

My equivalent query is like
```
SELECT  bizdate, groupArray(last_px) as px_array
FROM table
GROUP BY bizdate
```
last_px is decimal type, and I can confirm datetime and str not causing the problem.

It seems #248 had the same problem.

log
```
2022-02-17 06:53:29.263 - /api/gql
--
2022-02-17 14:53:29 | java.lang.StackOverflowError
2022-02-17 14:53:29 | at com.google.gson.stream.JsonWriter.string(JsonWriter.java:565)
2022-02-17 14:53:29 | at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:401)
2022-02-17 14:53:29 | at com.google.gson.stream.JsonWriter.value(JsonWriter.java:526)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.TypeAdapters$7.write(TypeAdapters.java:236)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.TypeAdapters$7.write(TypeAdapters.java:221)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2022-02-17 14:53:29 | at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)


```

**Comment by kseniiaguzeeva** [comment] 2022-02-17 07:10
Could you please give me an example of table DDL to reproduce the issue?

**Comment by simsicon** [comment] 2022-02-18 06:07
> Could you please give me an example of table DDL to reproduce the issue?

Like this, thanks

```
CREATE TABLE  IF NOT EXISTS tick (
    trade_date UInt32,
    orig_time Int64,
    last_px Decimal(9, 3),
)
ENGINE = MergeTree()
PARTITION BY trade_date
ORDER BY orig_time
;
```

**Comment by kseniiaguzeeva** [comment] 2022-02-21 10:06
I have a similar issue, but the stackoverflow error is different. Could you please also tell me the Clickhouse version? It will help me to find out the problem.
Do other applications can display the result?

**Comment by simsicon** [comment] 2022-02-22 05:04
> I have a similar issue, but the stackoverflow error is different. Could you please also tell me the Clickhouse version? It will help me to find out the problem. 

I am using clickhouse 22.1.3.7.

>Do other applications can display the result?

Sorry I have not tested it with other clients

**Comment by kseniiaguzeeva** [comment] 2022-03-23 07:14
The issue is fixed in the [latest release](https://github.com/dbeaver/cloudbeaver)

**Closed as completed by kseniiaguzeeva** 2022-03-23 07:14 UTC
Labels: x:clickhouse

**Comment by simsicon** [comment] 2022-04-06 09:17
> The issue is fixed in the [latest release](https://github.com/dbeaver/cloudbeaver)

Thanks, I am just looking forward to the release, and it would be nice if it is coming soon.

**Comment by kseniiaguzeeva** [comment] 2022-04-06 09:31
It's already published. You can upgrade your version.
